models:
  - name: stg_traffic_offenders
    description: >
      Staging model for traffic data. This model standardizes 
      data types from the spark-processed data source and drops city columns.
    columns:
      - name: violation_year_month
        description: "Violation year and month (YYYY-MM)"
        data_tests:
          - not_null
      - name: age
        description: Age of traffic offenders
      - name: gender
        description: Gender of traffic offenders
      - name: violation_type
        description: Violation type
      - name: roc_year
        description: Violation ROC year
      - name: month
        description: Violation month
      - name: year
        description: Violation year